---
title: "limpiar_fotos"
output: html_document
---

```{r}
if(!require(imager)) install.packages("imager")
library(imager)

# Usaremos 1024x1024 como un buen balance de calidad/velocidad.
nuevo_ancho <- 1024
nuevo_alto <- 1024

# Obtenemos la lista de archivos
archivos <- list.files("fotos_raw/", pattern = "\\.(jpg|jpeg|png)$", full.names = TRUE, ignore.case = TRUE)

# Bucle para procesar cada imagen
for (archivo in archivos) {
  
  # load.image ya normaliza los valores automáticamente al rango [0,1]
  img <- load.image(archivo)
  
  # Redimensionar (mismos px)
  img_final <- resize(img, size_x = nuevo_ancho, size_y = nuevo_alto)
  
  # Guardar imagen procesada
  nombre_archivo <- tools::file_path_sans_ext(basename(archivo))
  ruta_salida <- paste0("fotos_clean/", "clean_", nombre_archivo, ".jpg")
  
  save.image(img_final, ruta_salida)
  
  print(paste("Procesada:", nombre_archivo, "-> Dimensiones:", dim(img_final)[1], "x", dim(img_final)[2], " -> Rango: [", round(range(img_final)[1],2),",", round(range(img_final)[2],2), "]"))
}
```

```{r}
# Comprobación de que las imágenes estan en la carpeta correspondiente
img_jpg <- load.image("fotos_clean/clean_cielo_dia_luna.jpg")
img_jpg2 <- load.image("fotos_clean/clean_cielo_dia_nubes.jpg")

range(img_jpg)
range(img_jpg2)
```

